### ISSUE TITLE
Metis hits a Segmentation fault when running _METIS_PartGraphKway

### ISSUE THREAD

**Issue by poppingtonic** [benedekrozemberczki/ClusterGCN#1]
+ I'm using the default test input files.

+ I've attached pdb screenshot during the run.

+ Environment:
Ubuntu 18.04
Anaconda (Python 3.7.3),  
torch-geometric==1.3.0
torch-scatter==1.3.0
torch-sparse==0.4.0
torch-spline-conv==1.1.0
metis==0.2a.4

PDB Error
![Screenshot from 2019-07-04 13-56-16](https://user-images.githubusercontent.com/5781617/60661609-efe11500-9e62-11e9-8fb9-a1ad775a9e45.png)

Requirements.txt
![Screenshot from 2019-07-04 14-02-14](https://user-images.githubusercontent.com/5781617/60661902-b78e0680-9e63-11e9-9e33-64a4c3a3f4c3.png)

**Comment by yaokl-nju** [comment]
I got the same problem.

**Comment by poppingtonic** [comment]
The problem is the python version. I don't think the symbols provided to support the `metis` library are available in python 3.6 and above, so it is better to test this out in python 3.5. Simply create a conda environment with python 3.5 and it will work well enough.
