### ISSUE TITLE
Cannot run main.py

### ISSUE THREAD

**Issue by linkerlin** [benedekrozemberczki/ClusterGCN#10]
src/main.py --epochs 100
+-------------------+----------------------+
|     Parameter     |        Value         |
+===================+======================+
| Cluster number    | 10                   |
+-------------------+----------------------+
| Clustering method | metis                |
+-------------------+----------------------+
| Dropout           | 0.500                |
+-------------------+----------------------+
| Edge path         | ./input/edges.csv    |
+-------------------+----------------------+
| Epochs            | 100                  |
+-------------------+----------------------+
| Features path     | ./input/features.csv |
+-------------------+----------------------+
| Layers            | [16, 16, 16]         |
+-------------------+----------------------+
| Learning rate     | 0.010                |
+-------------------+----------------------+
| Seed              | 42                   |
+-------------------+----------------------+
| Target path       | ./input/target.csv   |
+-------------------+----------------------+
| Test ratio        | 0.900                |
+-------------------+----------------------+

Metis graph clustering started.

Traceback (most recent call last):
  File "src/main.py", line 24, in <module>
    main()
  File "src/main.py", line 18, in main
    clustering_machine.decompose()
  File "/Users/linmiao/gits/ClusterGCN/src/clustering.py", line 38, in decompose
    self.metis_clustering()
  File "/Users/linmiao/gits/ClusterGCN/src/clustering.py", line 56, in metis_clustering
    (st, parts) = metis.part_graph(self.graph, self.args.cluster_number)
  File "/usr/local/lib/python3.7/site-packages/metis.py", line 765, in part_graph
    graph = networkx_to_metis(graph)
  File "/usr/local/lib/python3.7/site-packages/metis.py", line 574, in networkx_to_metis
    for i in H.node:
AttributeError: 'Graph' object has no attribute 'node'

**Comment by NIRVANALAN** [comment]
networkx==2.3 solved this problem
