### ISSUE TITLE
How to install metis? my metis don't have attribute part graph! help!!!!! thanks

### ISSUE THREAD

**Issue by MrHaoG** [benedekrozemberczki/ClusterGCN#11]

**Comment by benedekrozemberczki** [comment]
The problem is that the people who wrote the METIS wrapper created a wrapper that does not work with the new NetworkX. What is your version of NX?

**Comment by MrHaoG** [comment]
thank u very much

**Comment by james77777778** [comment]
I met the same problem and I solved it by slightly modifying the original metis wrapper to support the lastest networkx.
You can check my repo:
https://github.com/james77777778/metis_python
