### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by dkdk-ddk** [benedekrozemberczki/ClusterGCN#15]
Hi there:
  Thank you for your great work, I've finally got the code running.
  To make the installation in `README.md` more precise & complete. You may want to add the following dependancies:
- torch_spline_conv == 1.0.4
- torch_sparse == 0.2.2
- torch_scatter == 1.0.4
- torch_cluster == 1.1.5 (strict)

**Comment by benedekrozemberczki** [comment]
Thank You!
