### ISSUE TITLE
RuntimeError: Could not locate METIS dll. 

### ISSUE THREAD

**Issue by tanjia123456** [benedekrozemberczki/ClusterGCN#25]
hello,when I run main.py, the error massage appears:

raise RuntimeError('Could not locate METIS dll. Please set the METIS_DLL environment variable to its full path.')
RuntimeError: Could not locate METIS dll. Please set the METIS_DLL environment variable to its full path.

do you know how to solve it?

**Comment by benedekrozemberczki** [comment]
Please download metis.
