### ISSUE TITLE
TypeError: object of type 'int' has no len()

### ISSUE THREAD

**Issue by tanjia123456** [benedekrozemberczki/ClusterGCN#26]
hello, when I run main.py, I found the error message:
File "D:\anaconda3.4\lib\site-packages\pymetis\__init__.py", line 44, in _prepare_graph
    for i in range(len(adjacency)):
TypeError: object of type 'int' has no len()

I have installed pymetis package to solve the metis.dll, this error occurs in the pymetis\__init__.py.
do you know how to solve it?

**Comment by benedekrozemberczki** [comment]
Please use linux.
