### ISSUE TITLE
The error of metis, Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yiyang-wang** [benedekrozemberczki/ClusterGCN#28]
I found that I can use the random model to divide the graph, but when using Metis, the code will terminate abnormally. I want to ask what causes this. I change "IDXTYPEWIDTH = os.getenv('METIS_IDXTYPEWIDTH', '32')" in metis.py (line 31) to "IDXTYPEWIDTH = os.getenv('METIS_IDXTYPEWIDTH', '64')", but it doesn't work!!!

python src/main.py
+-------------------+----------------------+
|     Parameter     |        Value         |
+===================+======================+
| Cluster number    | 10                   |
+-------------------+----------------------+
| Clustering method | metis                |
+-------------------+----------------------+
| Dropout           | 0.500                |
+-------------------+----------------------+
| Edge path         | ./input/edges.csv    |
+-------------------+----------------------+
| Epochs            | 200                  |
+-------------------+----------------------+
| Features path     | ./input/features.csv |
+-------------------+----------------------+
| Layers            | [16, 16, 16]         |
+-------------------+----------------------+
| Learning rate     | 0.010                |
+-------------------+----------------------+
| Seed              | 42                   |
+-------------------+----------------------+
| Target path       | ./input/target.csv   |
+-------------------+----------------------+
| Test ratio        | 0.900                |
+-------------------+----------------------+

Metis graph clustering started.

Segmentation fault (core dumped)

**Comment by Schrodinger-E** [comment]
you can use pymetis instead metis...
