### ISSUE TITLE
Segmentation fault While running main.py on Ubuntu

### ISSUE THREAD

**Issue by alamsaqib** [benedekrozemberczki/ClusterGCN#5]
while i am running main.py i am getting the segmentation fault error on Ubuntu.

python3 main.py --epochs 100

+-------------------+----------------------------------------------------------+
|     Parameter     |                          Value                           |
+===================+==========================================================+
| Cluster number    | 10                                                       |
+-------------------+----------------------------------------------------------+
| Clustering method | metis                                                    |
+-------------------+----------------------------------------------------------+
| Dropout           | 0.500                                                    |
+-------------------+----------------------------------------------------------+
| Edge path         | /home/User/Desktop/ClusterGCN-master/input/edges.csv |
+-------------------+----------------------------------------------------------+
| Epochs            | 100                                                      |
+-------------------+----------------------------------------------------------+
| Features path     | /home/User/Desktop/ClusterGCN-                       |
|                   | master/input/features.csv                                |
+-------------------+----------------------------------------------------------+
| Layers            | [16, 16, 16]                                             |
+-------------------+----------------------------------------------------------+
| Learning rate     | 0.010                                                    |
+-------------------+----------------------------------------------------------+
| Seed              | 42                                                       |
+-------------------+----------------------------------------------------------+
| Target path       | /home/User/Desktop/ClusterGCN-                       |
|                   | master/input//target.csv                                 |
+-------------------+----------------------------------------------------------+
| Test ratio        | 0.900                                                    |
+-------------------+----------------------------------------------------------+

Metis graph clustering started.

> Segmentation fault

**Comment by benedekrozemberczki** [comment]
How much memory do you have?

**Comment by Satonio1** [comment]
I get the same error

**Comment by Satonio1** [comment]
@benedekrozemberczki How memory do I need to run the input?

**Comment by Satonio1** [comment]
@alamsaqib I fix the error.You should change "IDXTYPEWIDTH  = os.getenv('METIS_IDXTYPEWIDTH', '32')" in metis.py (line 31) to "IDXTYPEWIDTH  = os.getenv('METIS_IDXTYPEWIDTH', '64')".Then the program works.

**Comment by yiyang-wang** [comment]
> @alamsaqib I fix the error.You should change "IDXTYPEWIDTH = os.getenv('METIS_IDXTYPEWIDTH', '32')" in metis.py (line 31) to "IDXTYPEWIDTH = os.getenv('METIS_IDXTYPEWIDTH', '64')".Then the program works.

I try this, but it doesn't work to me.
