### ISSUE TITLE
For ppi

### ISSUE THREAD

**Issue by guochengqian** [benedekrozemberczki/ClusterGCN#6]
Hello. Thanks for your work and code. It's great that Cluster-GCN achieves great performance in PPI datasets.  But it seems that you have not opened source the code for PPI node classification.  

Do you find the best model on validation dataset at first then test on the unseen test dataset?
I notice that GraphStar now is the SOTA. However, they don't use the validation dataset and directly find the best model on test dataset.

Can you share code of PPI with us and mention how to split dataset in the readme file? It's important for others to follow your great job.

**Comment by benedekrozemberczki** [comment]
This is not my model :).

**Comment by Yfhu1103** [comment]
> Hello. Thanks for your work and code. It's great that Cluster-GCN achieves great performance in PPI datasets. But it seems that you have not opened source the code for PPI node classification.
> 
> Do you find the best model on validation dataset at first then test on the unseen test dataset?
> I notice that GraphStar now is the SOTA. However, they don't use the validation dataset and directly find the best model on test dataset.
> 
> Can you share code of PPI with us and mention how to split dataset in the readme file? It's important for others to follow your great job.

Have you found the implemenation of clusterGCN on PPI dataset?
