### ISSUE TITLE
Metis Segmentation Fault (Cored Dumped)

### ISSUE THREAD

**Issue by voladorlu** [benedekrozemberczki/ClusterGCN#8]
Hi, @benedekrozemberczki  thanks so much for sharing the code. After following the installation instructions, it seems to failing to install the metis for python. I can run the main.py with random partition method. However, I always get "aborted (core dumped)" when using metis partition method. Could you help me to target issue? It'd better if you can share some suggestions.

1) Download metis-5.1.0.tar.gz from http://glaros.dtc.umn.edu/gkhome/metis/metis/download and unpack it
2) cd metis-5.1.0
3) make config shared=1 prefix=~/.local/
4) make install
5) export METIS_DLL=~/.local/lib/libmetis.so

Here is an official example to check metis. However, I always get "aborted (core dumped)" error.
`
>>> import networkx as nx
>>> import metis
>>> G = metis.example_networkx()
>>> (edgecuts, parts) = metis.part_graph(G, 3)
`

===== My System Information ====
Ubuntu 18, python 3.7

**Comment by benedekrozemberczki** [comment]
Look at earlier issues.
